export const FETCH_LIST_REGISTER_FORM = 'FETCH_LIST_REGISTER_FORM'
export const CONFIRM_REGISTER_FORM = 'CONFIRM_REGISTER_FORM';
export const DELETE_REGISTER_FORM = 'DELETE_REGISTER_FORM';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';